### ISSUE TITLE
Fails to compile with GCC 11.1

### ISSUE THREAD

**Issue by M-Reimer** [vdr-projects/vdr-plugin-mp3#2]
```
data-mp3.c:46:27: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   46 | const char *excl_pl[] = { "*"PLAYLISTEXT,"*.jpg","*.gif","*.png",0 };
      |                           ^
data-mp3.c:553:33: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
  553 |   static const char *spec[] = { "*"PLAYLISTEXT,0 };
      |                                 ^
data-mp3.c: In member function ‘virtual bool cPlayList::Load()’:
data-mp3.c:412:41: error: ordered comparison of pointer with integer zero (‘char*’ and ‘int’)
  412 |     while(fgets(buffer,sizeof(buffer),f)>0) {
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from decoder-snd.c:40:
decoder-snd.c: In member function ‘virtual bool cSndDecoder::Start()’:
decoder-snd.c:179:14: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘sf_count_t’ {aka ‘long int’} [-Wformat=]
  179 |     d(printf("snd: open rate=%d frames=%lld channels=%d format=0x%x seek=%d\n",
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  180 |              file.sfi.samplerate,file.sfi.frames,file.sfi.channels,file.sfi.format,file.sfi.seekable))
      |                                  ~~~~~~~~~~~~~~~
      |                                           |
      |                                           sf_count_t {aka long int}
common.h:36:17: note: in definition of macro ‘d’
   36 | #define d(x) { (x); }
      |                 ^
decoder-snd.c:179:43: note: format string is defined here
  179 |     d(printf("snd: open rate=%d frames=%lld channels=%d format=0x%x seek=%d\n",
      |                                        ~~~^
      |                                           |
      |                                           long long int
      |                                        %ld
In file included from decoder-snd.c:40:
decoder-snd.c: In member function ‘virtual bool cSndDecoder::Skip(int, float)’:
decoder-snd.c:275:14: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘sf_count_t’ {aka ‘long int’} [-Wformat=]
  275 |     d(printf("snd: skip: secs=%d fsecs=%f frames=%lld current=%lld new=%lld\n",Seconds,fsecs,frames,file.Seek(0,true),newpos))
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~               ~~~~~~
      |                                                                                              |
      |                                                                                              sf_count_t {aka long int}
common.h:36:17: note: in definition of macro ‘d’
   36 | #define d(x) { (x); }
      |                 ^
decoder-snd.c:275:53: note: format string is defined here
  275 |     d(printf("snd: skip: secs=%d fsecs=%f frames=%lld current=%lld new=%lld\n",Seconds,fsecs,frames,file.Seek(0,true),newpos))
      |                                                  ~~~^
      |                                                     |
      |                                                     long long int
      |                                                  %ld
In file included from decoder-snd.c:40:
decoder-snd.c:275:14: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 5 has type ‘sf_count_t’ {aka ‘long int’} [-Wformat=]
  275 |     d(printf("snd: skip: secs=%d fsecs=%f frames=%lld current=%lld new=%lld\n",Seconds,fsecs,frames,file.Seek(0,true),newpos))
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      ~~~~~~~~~~~~~~~~~
      |                                                                                                              |
      |                                                                                                              sf_count_t {aka long int}
common.h:36:17: note: in definition of macro ‘d’
   36 | #define d(x) { (x); }
      |                 ^
decoder-snd.c:275:66: note: format string is defined here
  275 |     d(printf("snd: skip: secs=%d fsecs=%f frames=%lld current=%lld new=%lld\n",Seconds,fsecs,frames,file.Seek(0,true),newpos))
      |                                                               ~~~^
      |                                                                  |
      |                                                                  long long int
      |                                                               %ld
In file included from decoder-snd.c:40:
decoder-snd.c:275:14: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 6 has type ‘sf_count_t’ {aka ‘long int’} [-Wformat=]
  275 |     d(printf("snd: skip: secs=%d fsecs=%f frames=%lld current=%lld new=%lld\n",Seconds,fsecs,frames,file.Seek(0,true),newpos))
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                        ~~~~~~
      |                                                                                                                       |
      |                                                                                                                       sf_count_t {aka long int}
common.h:36:17: note: in definition of macro ‘d’
   36 | #define d(x) { (x); }
      |                 ^
decoder-snd.c:275:75: note: format string is defined here
  275 |     d(printf("snd: skip: secs=%d fsecs=%f frames=%lld current=%lld new=%lld\n",Seconds,fsecs,frames,file.Seek(0,true),newpos))
      |                                                                        ~~~^
      |                                                                           |
      |                                                                           long long int
      |                                                                        %ld
decoder-snd.c:285:52: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘sf_count_t’ {aka ‘long int’} [-Wformat=]
  285 |       printf("snd: skipping to %02d:%02d (frame %lld)\n",i/60,i%60,frames);
      |                                                 ~~~^               ~~~~~~
      |                                                    |               |
      |                                                    long long int   sf_count_t {aka long int}
      |                                                 %ld
decoder.c: In member function ‘bool cFileInfo::FileInfo(bool)’:
decoder.c:224:44: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘__fsblkcnt64_t’ {aka ‘long unsigned int’} [-Wformat=]
  224 |           if(Removable()) FsID=aprintf("%llx:%llx",sfs.f_blocks,sfs.f_files);
      |                                         ~~~^       ~~~~~~~~~~~~
      |                                            |           |
      |                                            |           __fsblkcnt64_t {aka long unsigned int}
      |                                            long long unsigned int
      |                                         %lx
decoder.c:224:49: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘__fsfilcnt64_t’ {aka ‘long unsigned int’} [-Wformat=]
  224 |           if(Removable()) FsID=aprintf("%llx:%llx",sfs.f_blocks,sfs.f_files);
      |                                              ~~~^               ~~~~~~~~~~~
      |                                                 |                   |
      |                                                 |                   __fsfilcnt64_t {aka long unsigned int}
      |                                                 long long unsigned int
      |                                              %lx
make: *** [Makefile:193: data-mp3.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by martinkg** [comment]
fixed with attached patch ?
[vdr-mp3-fix-C++11-warning.patch.txt](https://github.com/vdr-projects/vdr-plugin-mp3/files/6539335/vdr-mp3-fix-C%2B%2B11-warning.patch.txt)

**Comment by M-Reimer** [comment]
Yes, this fixed it. Thank you.
